services:
  smoke-test-fast:
    image: ghcr.io/markcallen/flutter-setup-sdk-base:latest
    container_name: flutter-setup-smoke-fast
    volumes:
      - .:/app
    entrypoint: ["/bin/bash", "tests/fast_smoke_test.sh"]
